### ISSUE TITLE
how do i install this

### ISSUE THREAD

**Issue by MegaTKC** [MCPI-Revival/PiMine#1]

**Comment by TheBrokenRail** [comment]
This isn't completed yet, so cannot be installed yet.

**Comment by mobilegmYT** [comment]
> This isn't completed yet, so cannot be installed yet.

One could probably say this about 99% of all repos in this organization.

**Comment by TheBrokenRail** [comment]
> One could probably say this about 99% of all repos in this organization.

And they wouldn't be wrong. This organization is filled with incomplete prototypes.

**Comment by mobilegmYT** [comment]
*cough cough* MFD *cough cough wheeze*
